sudo: false
language: python
cache: pip

script:
  - make test

install:
  - pip install -r requirements.txt

matrix:
  include:
    - python: "3.5"
    - python: "3.6"

notifications:
  email: false
  irc: "irc.freenode.org#XelNext"
