sudo: false
language: python
cache: pip

script:
  - make test

install:
  - make update

matrix:
  include:
    - name: "Python 3.5"
      python: 3.5
    - name: "Python 3.6"
      python: 3.6
    - name: "Linting"
      python: 3.6
      script:
        - make lint

notifications:
  email: false
  irc: "irc.freenode.org#XelNext"
